### ISSUE TITLE
Feasible way of periodic status update mail implementation

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [cognizance-amrita/cognizance_cms#39]
Will be great if this could be done within the django app using the status update template provided in the adminapp HTML templates directory

**Comment by tejas15802** [comment]
[django_cron job](https://www.youtube.com/watch?v=MDjVZ6KIUic&ab_channel=SuperCoders)
might help

**Comment by tejas15802** [comment]
I'm looking for help regarding this issue. If someone knows how to do you can take this issue.

**Comment by sanjay-thiyagarajan** [comment]
Found an alternative way through Google Groups. Trashing this issue :)
