### ISSUE TITLE
Forgot Password Broken

### ISSUE THREAD

**Issue by tejas15802** [cognizance-amrita/cognizance_cms#78]
Forgot password broken after the recent commit

**Comment by tejas15802** [comment]
@sanjay-thiyagarajan  commenting out `# path('<str:member_name>/',views.member),` fixes the issue. shall I make the change and given an Pull Requests.... I made sure my current repository as this repository...

**Comment by sanjay-thiyagarajan** [comment]
No...please don't comment it. I'll add a fallback later

**Comment by tejas15802** [comment]
okay

**Comment by tejas15802** [comment]
@sanjay-thiyagarajan please do close this issue once u find that its in working state....
